#!/bin/bash
EXTERNAL_OUTPUT="HDMI-1"
INTERNAL_OUTPUT="eDP-1"
INTERNAL_ARGS="--mode 2880x1620 --scale 1x1 --filter nearest"
EXTERNAL_ARGS="--auto --scale-from 2880x1620"
# if we don't have a file, start at zero
if [ ! -f "/tmp/monitor_mode.dat" ] ; then
  monitor_mode="all"

# otherwise read the value from the file
else
  monitor_mode=`cat /tmp/monitor_mode.dat`
fi

if [ $monitor_mode = "all" ]; then
        monitor_mode="EXTERNAL"
        xrandr --output $INTERNAL_OUTPUT --off --output $EXTERNAL_OUTPUT $EXTERNAL_ARGS
elif [ $monitor_mode = "EXTERNAL" ]; then
        monitor_mode="INTERNAL"
        xrandr --output $INTERNAL_OUTPUT $INTERNAL_ARGS --output $EXTERNAL_OUTPUT --off
elif [ $monitor_mode = "INTERNAL" ]; then
        monitor_mode="CLONES"
        xrandr --output $INTERNAL_OUTPUT $INTERNAL_ARGS --output $EXTERNAL_OUTPUT $EXTERNAL_ARGS --same-as $INTERNAL_OUTPUT
else
        monitor_mode="all"
        xrandr --output $INTERNAL_OUTPUT $INTERNAL_ARGS --output $EXTERNAL_OUTPUT $EXTERNAL_ARGS --left-of $INTERNAL_OUTPUT
fi
echo "${monitor_mode}" > /tmp/monitor_mode.dat
