#!/bin/bash

#i3 startup script
xrandr --output eDP1 --auto --mode 2880x1620 --output HDMI1 --scale-from 2880x1620
amixer -c 0 sset "Auto-Mute Mode" Enabled
xsettingsd &
picom -bc &
fcitx &
flameshot &
redshift &
nm-applet &
blueman-applet &
pamac-tray &
clipit &
#fix_xcursor &
ff-theme-util &
pasystray &
languagetool --http --port 8081 &

